{% set version = "1.10.0" %}

package:
  name: libgcrypt
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-{{ version }}.tar.bz2
  sha256: 6a00f5c05caa4c4acc120c46b63857da0d4ff61dc4b4b03933fa8d46013fae81

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - libgpg-error

test:
  commands:
    - test -f ${PREFIX}/lib/libgcrypt${SHLIB_EXT}  # [linux]

about:
  home: https://gnupg.org/software/index.html
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - COPYING.LIB
    - COPYING
    - LICENSES
  license_family: GPL
  summary: a general purpose cryptographic library originally based on code from GnuPG.

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
    - mbargull
    - xhochy
