{% set version = "1.10.2" %}

package:
  name: libgcrypt
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-{{ version }}.tar.bz2
  sha256: 3b9c02a004b68c256add99701de00b383accccf37177e0d6c58289664cce0c03
  patches:
    - rCfa21ddc158b5d7b5900856e5b131071302217a51.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - libgpg-error

test:
  commands:
    - test -f ${PREFIX}/lib/libgcrypt${SHLIB_EXT}  # [linux]

about:
  home: https://gnupg.org/software/index.html
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - COPYING.LIB
    - COPYING
    - LICENSES
  license_family: GPL
  summary: a general purpose cryptographic library originally based on code from GnuPG.

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
    - mbargull
    - xhochy
