{% set version = "1.9.2" %}

package:
  name: libgcrypt
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-{{ version }}.tar.bz2
  sha256: b2c10d091513b271e47177274607b1ffba3d95b188bbfa8797f948aec9053c5a

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libgpg-error

test:
  commands:
    - test -f ${PREFIX}/lib/libgcrypt${SHLIB_EXT}  # [linux]

about:
  home: https://gnupg.org/software/index.html
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - COPYING.LIB
    - COPYING
    - LICENSES
  license_family: GPL
  summary: a general purpose cryptographic library originally based on code from GnuPG.

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
    - mbargull
